# Generated by Django 4.1.2 on 2023-01-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_activityfeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityfeed',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
