# Generated by Django 4.1.2 on 2023-01-17 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_activityfeed_associated_action_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityfeed',
            name='related_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
