# Generated by Django 4.1.2 on 2023-03-11 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_activityfeed_related_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='date_accepted',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='profile_acceptor',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='profile_requestor',
        ),
        migrations.AddField(
            model_name='friendship',
            name='friends',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED')], max_length=255)),
                ('requestee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestee', to=settings.AUTH_USER_MODEL)),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
