# Generated by Django 4.1.2 on 2024-01-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_activityfeed_action_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='registryuser',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
