# Generated by Django 4.1.2 on 2024-01-27 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_registryuser_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_image', to=settings.AUTH_USER_MODEL),
        ),
    ]
