# Generated by Django 4.1.2 on 2024-01-27 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_profileimage_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityfeed',
            name='dismissed_by',
            field=models.ManyToManyField(related_name='dismissed_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
