import type { NextPage } from "next";
import Head from "next/head";

// Components
import LandingPage from "../components/LandingPage";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Registry</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LandingPage />
    </div>
  );
};

export default Home;
