version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    environment:
      - GOOGLE_AUD_CLAIM=$GOOGLE_AUD_CLAIM
      - NEXT_PUBLIC_FRONTEND_BASE_URL=$NEXT_PUBLIC_FRONTEND_BASE_URL
      - POSTGRES_PASSWORD=$${{ secrests.POSTGRES_PASSWORD }}
      - POSTGRES_USER=$${{ secrests.POSTGRES_USER}}
    depends_on:
      - db
    restart: always
    links:
      - "db:database"

  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      - POSTGRES_PASSWORD=$${{ secrests.POSTGRES_PASSWORD }}
      - POSTGRES_USER=$${{ secrests.POSTGRES_USER}}
    ports:
      - 5432:5432
