# Generated by Django 4.1.2 on 2022-12-17 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftitem',
            name='url',
        ),
        migrations.CreateModel(
            name='GiftItemUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255)),
                ('gift_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.giftitem')),
            ],
        ),
    ]
