# Generated by Django 4.1.4 on 2022-12-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registryuser',
            name='sub',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
