# Generated by Django 4.1.2 on 2023-01-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='date_accepted',
            field=models.DateField(blank=True, null=True),
        ),
    ]
