# Generated by Django 4.1.2 on 2023-01-15 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_friendship_created_at_friendship_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registryuser',
            name='relationships',
        ),
    ]
