# Generated by Django 4.1.2 on 2023-01-16 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_activityfeed_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityfeed',
            name='associated_action_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
