name: Backend Integration CI 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: zander 
          POSTGRES_PASSWORD: registrydbtest 
          POSTGRES_DB: db 
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
        name: Checkout code
        uses: actions/checkout@v3

        name: Docker compose 
        uses: isbang/compose-action@v1.4.1
        with:
            up-flags: "--env-file .env up --remove-orphans --force-recreate -V -d"
            compose-file: "./docker-compose.yml"
